# SPDX-License-Identifier: MPL-2.0
name: Setup AUR SSH Known Hosts
description: Verify and configure AUR SSH host key with fingerprint verification

runs:
  using: composite
  steps:
    - name: Configure SSH Known Hosts for AUR
      shell: bash -euo pipefail {0}
      run: |
        # shellcheck shell=bash
        # shellcheck source=../../scripts/common.sh
        source "$GITHUB_WORKSPACE/.github/scripts/common.sh"

        aur_key_file=$(mktemp)
        # Remove temporary key file on exit
        trap 'rm -f "$aur_key_file"' EXIT

        mkdir -p "$HOME/.ssh"
        chmod 700 "$HOME/.ssh"

        # Pinned AUR Ed25519 fingerprint
        expected_fingerprint="SHA256:RFzBCUItH9LZS0cKB5UE6ceAYhBD5C8GeOBip8Z11+4"

        # Retry ssh-keyscan to tolerate transient network failures
        if ! retry_command "${RETRY_MAX_ATTEMPTS:-3}" "${RETRY_DELAY_BASE:-2}" sh -c "ssh-keyscan -t ed25519 aur.archlinux.org > $aur_key_file 2>/dev/null && [ -s $aur_key_file ]"; then
          echo "::error::Failed to fetch AUR SSH host key after ${RETRY_MAX_ATTEMPTS:-3} attempts"
          exit 1
        fi

        scanned_fingerprint=$(ssh-keygen -lf "$aur_key_file" | awk '{print $2}')

        if [ "$scanned_fingerprint" != "$expected_fingerprint" ]; then
          echo "::error::AUR SSH fingerprint mismatch! Expected: $expected_fingerprint, Got: $scanned_fingerprint"
          exit 1
        fi

        cat "$aur_key_file" >> "$HOME/.ssh/known_hosts"
        chmod 600 "$HOME/.ssh/known_hosts"
        echo "AUR host key verified and added"
