name: Setup AUR SSH Known Hosts
description: Verify and configure AUR SSH host key with fingerprint verification

runs:
  using: composite
  steps:
    - name: Configure SSH Known Hosts for AUR
      shell: bash -euo pipefail {0}
      run: |
        # shellcheck shell=bash
        # Cleanup on exit (success or failure)
        trap 'rm -f /tmp/aur_key' EXIT

        mkdir -p "$HOME/.ssh"
        chmod 700 "$HOME/.ssh"

        # Official AUR Ed25519 fingerprint
        expected_fingerprint="SHA256:RFzBCUItH9LZS0cKB5UE6ceAYhBD5C8GeOBip8Z11+4"

        # Fetch host key with retry
        max_attempts=3
        for attempt in $(seq 1 "$max_attempts"); do
          if ssh-keyscan -t ed25519 aur.archlinux.org > /tmp/aur_key 2>/dev/null && [ -s /tmp/aur_key ]; then
            break
          fi
          echo "Attempt $attempt failed, retrying..."
          sleep $((attempt * 2))
          if [ "$attempt" -eq "$max_attempts" ]; then
            echo "::error::Failed to fetch AUR SSH host key after $max_attempts attempts"
            exit 1
          fi
        done

        scanned_fingerprint=$(ssh-keygen -lf /tmp/aur_key | awk '{print $2}')

        if [ "$scanned_fingerprint" != "$expected_fingerprint" ]; then
          echo "::error::AUR SSH fingerprint mismatch! Expected: $expected_fingerprint, Got: $scanned_fingerprint"
          exit 1
        fi

        cat /tmp/aur_key >> "$HOME/.ssh/known_hosts"
        chmod 600 "$HOME/.ssh/known_hosts"
        echo "AUR host key verified and added"
